### ISSUE TITLE
stray <div>

### ISSUE THREAD

**Issue by jmbott** [SEL-Columbia/SEL-Columbia.github.io#128]
remove stray <div>
http://qsel.columbia.edu/shared-solar/

**Comment by jmbott** [comment]
While we are at it a few more stray tags on these pages, 

http://qsel.columbia.edu/quench/
http://qsel.columbia.edu/scale-up-initiative/
http://qsel.columbia.edu/millenium-villages-project/
http://qsel.columbia.edu/sustainable-energy-solutions-program-in-west-africa/
http://qsel.columbia.edu/smart-solar-irrigation/

**Comment by vr2262** [comment]
Any others? If not, please merge #130
