### ISSUE TITLE
Edit Revisit Contact

### ISSUE THREAD

**Issue by jmbott** [SEL-Columbia/SEL-Columbia.github.io#148]
Switch to Vijay

https://revisit.global/
https://github.com/SEL-Columbia/Revisit-Website

**Comment by vr2262** [comment]
Er... I don't know if Vijay's the right person to be receiving those e-mails. I'll change it to my own.

**Comment by vr2262** [comment]
Closed in https://github.com/SEL-Columbia/Revisit-Website/commit/16652c54e9bd9d31909fecb204797fde16de3905
