### ISSUE TITLE
Figure out how to get Post excerpts (including images, headlines, etc.) to display on main pages such as Blogs

### ISSUE THREAD

**Issue by Nasafato** [SEL-Columbia/SEL-Columbia.github.io#16]
**What blog posts look like as displayed on the Blog page in production**
<img width="750" alt="screen shot 2015-12-05 at 5 09 55 pm" src="https://cloud.githubusercontent.com/assets/7004114/11610522/0d3be07c-9b73-11e5-954e-9e743739f3eb.png">

Because post content is contained inside each post in `blog/_posts/`, such as images, the text, and whatever else is needed, we need to figure out how to extract, say, the first image or two, as well as the first paragraph or so of text content to display on the main Blog page as a preview.

Right now, I'm using `{{ post.content | strip_html | truncatewords: 50 }}` as a way to get the first 50 words of a post, but it shows any HTML embedded in the text content as pure text, instead of, for example, a link.
Jekyll also has a feature called excerpting, and [here's](https://gist.github.com/benbalter/5555369) an example of this. You use `{{ post.excerpt }}`.

**Comment by vr2262** [comment]
@Nasafato in my `vr2262-issue-#16` branch I have

1. Killed all references to `wp-content`
  - Now all the references are to `/assets/images/blog/`
  - Some of the `wp-content` references were to images that don't seem to exist anywhere.
2. Included a bit of code in `blog/index.md` to pull out the first image from a post and include it in the blog index listing.
  - Here is the code: https://github.com/SEL-Columbia/SEL-Columbia.github.io/commit/e678d5a831c7efe3a96f4f94c8e10ee866dd093b
  - I looked at the current sel.columbia.edu and I'm pretty sure that's what the Wordpress site is doing anyway.

**Comment by vr2262** [comment]
I didn't touch `index.html` because I figured that's still in flux. But the same principle should apply.

**Comment by vr2262** [comment]
Closed via #51
