### ISSUE TITLE
come up with a mapping from our site to jekyll constructs

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#2]
projects -> posts or collections?
about page staff -> posts/collections?

We want blog entries and other pages to be simple to edit.

**Comment by Nasafato** [comment]
I think we pretty much know what the mapping is at this point. We have our directory structure. The question is — where is the best place to put the alumni and team folders? I personally dislike having them in the root directory, and feel that they belong in the about page folder.

**Comment by chrisnatali** [comment]
Closing, but opened #32 to capture @Nasafato's comments
