### ISSUE TITLE
Move projects from their upper-level directories in dev to _posts in project folder

### ISSUE THREAD

**Issue by Nasafato** [SEL-Columbia/SEL-Columbia.github.io#20]
* Delhi Energy Project
* Liberia Electrification Project
* National Electrification Plan
* Nigera Electricity Access Program
* Potential for Regional Use of East Africa's Natural Gas
* Smart Solar Irrigation in Senegal
* Sustainable Energy Solutions Program
* Thousand Islands Project: Planning Rural Energy

ICT4D and Development Planning Projects
* Dristhi
* Millenium Villages Project
* Nigeria Scale-up Initiative
* Shared Solar
* Soil Doctor
* Quench

**Comment by vr2262** [comment]
@Nasafato @ssilwal is this done?

**Comment by chrisnatali** [comment]
@vr2262 is this closed by #90?

**Comment by vr2262** [comment]
@chrisnatali maybe? I'm not sure what this issue actually describes.

**Comment by chrisnatali** [comment]
This is done.
