### ISSUE TITLE
Evaluate prose for editing

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#22]
Want to see how difficult it will be for non-tech users to post content (may drive site organization)

**Comment by ssilwal** [comment]
To take a look at later, this may help:
http://allandenot.com/development/2015/01/11/blogging-like-a-dev-jekyll-github-prose-io.html

**Comment by vr2262** [comment]
@ssilwal nice find.
Looks like the niceties of using Prose come from a bunch of configuration settings:

https://github.com/prose/prose/wiki/Getting-Started
https://github.com/prose/prose/wiki/Prose-Configuration
https://github.com/hmfaysal/Notepad/blob/34ec357c86cb3d82fce5840909e4ee8f1bf625e0/_config.yml#L72

**Comment by vr2262** [comment]
@ssilwal ping
