### ISSUE TITLE
Fix jobs page

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#28]

**Comment by chrisnatali** [comment]
FYI, this looks fine when serving locally.  Only appears to be a problem when served via gh-pages.

**Comment by chrisnatali** [comment]
Still an issue.  Page is not being rebuilt by jekyll when pushing to master on github :(

**Comment by vr2262** [comment]
I'm seeing errors like
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://sel.columbia.edu/wp-content/themes/migration-theme/fonts/ProximaNova/ProximaNova-Regular.otf. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```
```
downloadable font: download failed (font-family: "ProximaNova" style:normal weight:bold stretch:normal src index:0): bad URI or cross-site access not allowed source: http://sel.columbia.edu/wp-content/themes/migration-theme/fonts/ProximaNova/ProximaNova-Bold.otf
```
```
Blocked loading mixed active content "http://sel.columbia.edu/wp-content/themes/migration-theme/style.css"
```

**Comment by chrisnatali** [comment]
Are you seeing this when running this branch locally?  Or only when going to sel-columbia.github.io/jobs (that's the only place where I see it).

**Comment by vr2262** [comment]
I couldn't run the branch locally without the change in #33

I suspect this may actually be the real issue...

**Comment by vr2262** [comment]
@chrisnatali you're not going to believe what the problem was:

https://github.com/SEL-Columbia/jobs had a `gh-pages` branch that was overriding the site's jobs page. I've deleted it.

From https://help.github.com/articles/using-jekyll-with-pages/#troubleshooting

> If you are having issues with your Jekyll Pages, make sure you are not using categories that are named the same as another project, as this could cause path conflicts. For example: if you have a blog post named 'resume' in your User Page repository and a project named 'resume' with a gh-pages branch, they will conflict with each other.

**Comment by chrisnatali** [comment]
woo-hoo!
