### ISSUE TITLE
team and alumni folder location

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#32]
From @Nasafato:  "The question is — where is the best place to put the alumni and team folders? I personally dislike having them in the root directory, and feel that they belong in the about page folder."

Following the guidelines [here](http://ben.balter.com/2015/02/20/jekyll-collections/#when-to-use-a-post-a-page-or-a-collection), it seems these should be in collections (since they're not really date/time ordered).

**Comment by vr2262** [comment]
@Nasafato @ssilwal is this done?
