### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by ssilwal** [SEL-Columbia/SEL-Columbia.github.io#50]
- Cut down on styling that is not being used.
- Add formatting for other pages (publications, jobs, etc.)

**Comment by ssilwal** [comment]
http://www.labnol.org/internet/remove-unused-css/28635/
- can use Audit on Chrome to check unused CSS rules on certain pages
-problem-- there are about 1500 unused rules for every page (unless I'm doing something wrong?)

**Comment by vr2262** [comment]
Try removing them and see what happens!

**Comment by ssilwal** [comment]
Check if same file is being applied to main site + dev site.

**Comment by vr2262** [comment]
@ssilwal ping

**Comment by vr2262** [comment]
I guess we can call this closed...
