### ISSUE TITLE
projects missing

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#56]
There are 14 projects listed on sel.columbia.edu, but only 8 in projects/_posts.  Did the migration miss these?

**Comment by chrisnatali** [comment]
Found them in an old commit.  The migration embedded some of the projects within the index.md:  https://github.com/SEL-Columbia/SEL-Columbia.github.io/blob/2b73a1b70dafb1d9f83e5b447c52af3dd047652e/projects/index.md

These should be made into projects/_posts entries.

**Comment by Nasafato** [comment]
The reason is that those projects are just "Related blog entries" - they don't have their own project page.

**Comment by vr2262** [comment]
@Nasafato so is this not an issue?

**Comment by Nasafato** [comment]
It's about whether or not you want to also have projects that are just links to Related Blog Posts. If so, then we'd have to implement something like that.

**Comment by vr2262** [comment]
I guess it makes sense to have posts that just link to blog entries...
