### ISSUE TITLE
Find and migrate Development Planning Toolkit site

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#58]
Make it a separate repo/gh-pages site.  Currently here:  http://modi.mech.columbia.edu/dpt/

**Comment by chrisnatali** [comment]
May be useful info from @vr2262 

"GitHub pages will serve user/repo at http://user.github.io/repo even if user/user.github.io exists."

Though, it's not clear how we might share layouts, etc across repo's without copying them.

**Comment by vr2262** [comment]
Just to clarify, GitHub will serve the `gh-pages` branch of `user/repo` at `http://user.github.io/repo`

**Comment by chrisnatali** [comment]
New [gh repo](https://github.com/SEL-Columbia/development-planning-toolkit) and [static site](http://sel-columbia.github.io/development-planning-toolkit/) for this.  We just need to link into new site (#99).  Assigning to @vr2262 to look over before closing.

**Comment by chrisnatali** [comment]
Closing in favor of #99
