### ISSUE TITLE
The post-author attribute is missing from all but one blog post

### ISSUE THREAD

**Issue by vr2262** [SEL-Columbia/SEL-Columbia.github.io#69]
RE: https://github.com/SEL-Columbia/SEL-Columbia.github.io/commit/2b73a1b70dafb1d9f83e5b447c52af3dd047652e#commitcomment-16302595

**Comment by chrisnatali** [comment]
I don't see what issue this addresses.  The commit comment [link](https://github.com/SEL-Columbia/SEL-Columbia.github.io/commit/2b73a1b70dafb1d9f83e5b447c52af3dd047652e#commitcomment-16302595) above doesn't reveal much.  

Why do we need post-author in addition to author?  Can't we consolidate?

**Comment by vr2262** [comment]
author is the full name
post-author is a "username" used for the /author endpoints

**Comment by vr2262** [comment]
http://sel.columbia.edu/author/cjn/

**Comment by chrisnatali** [comment]
K.  I think we need a strategy for managing users before doing too much more on this...duplication will make this harder to manage.

**Comment by vr2262** [comment]
We could have a file `_data/authors.yml` that has everyone's full name and "short name". I don't think we should get rid of the distinction if we want URLs to survive (http://sel.columbia.edu/author/cjn/)

**Comment by chrisnatali** [comment]
#71 is my proposal.

**Comment by vr2262** [comment]
Sounds good to me.
