### ISSUE TITLE
Move alumni to team and add id

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/SEL-Columbia.github.io#71]
It's simpler to consider alumni and current lab members as just members of the team (so we'll add them all to the team folder).  We'll need a "status" attribute to filter by e.g.,
```
{{ site.categories.team | where:"status","current" }}
```
 for the team page.  

This way we can reference team members (current and alumni) from other pages of the site via something like:
```
{% assign member = site.categories.team | where:"id",author.id %}
```
thereby reducing duplication.  

Haven't tested the filters...hope they work

**Comment by vr2262** [comment]
Seems like the author's `id` should be the `post-author` attribute from the Wordpress site.

**Comment by chrisnatali** [comment]
agreed
