### ISSUE TITLE
Organizing Jekyll and HTML so that it works well with Bootstrap

### ISSUE THREAD

**Issue by Nasafato** [SEL-Columbia/SEL-Columbia.github.io#8]
As you may know by now, the SEL site uses Bootstrap for styling. What's important here is to understand its grid-based system for organizing the content of the page.

This affects how we organize `_layouts`,` _posts`, and `_include` files.

Bootstrap's main grid element, which holds all other elements in the grid, is called `.container`.

Inside a `.container` element are `.row` elements.

Inside each `.row` element are columns — each row holds up to 12 columns. Columns are designated `.col-*-*`.

An example of how this would work is:
```html
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>6 columns</h1>
    </div>
    <div class="col-md-3">
      <h1>3 columns</h1>
    </div>
    <div class="col-md-3">
      <h1>3 columns</h1>
    </div>
  </div>
</div>
```

Thus, we need to make sure that our templating aligns with Bootstrap's grid-based organization.

This means the layout for each page, e.g. `default.html`, should have the following structure:
```html
<!-- rest of html -->

<div class="container">
  {{content}}
</div>

<!-- rest of html -->
```

This way, pages that use `default.html` as a layout can do whatever they want with the rows.

```html
---
layout: default
---

<div class="row">
  <div class class="col-md-12">
    {post.content}
  </div>
</div>

```

**Comment by Nasafato** [comment]
`page.html` is for when you click on posts. Each post in Jekyll gets its own page, and this page is structured according to `page.html`. Do note that `page.html` actually uses `default.html` as a layout as well, so it's sort of like a layout within a layout.

**Comment by vr2262** [comment]
@Nasafato I'm calling this issue done. Feel free to open it again if it is not.
